'use client'

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react'

export type Language = 'zh' | 'en'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}

interface LanguageProviderProps {
  children: ReactNode
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguage] = useState<Language>('zh')

  // 从localStorage加载语言设置
  useEffect(() => {
    const savedLanguage = localStorage.getItem('toolsabc-language') as Language
    if (savedLanguage && ['zh', 'en'].includes(savedLanguage)) {
      setLanguage(savedLanguage)
    }
  }, [])

  // 保存语言设置到localStorage
  useEffect(() => {
    localStorage.setItem('toolsabc-language', language)
    // 更新HTML的lang属性
    document.documentElement.lang = language
  }, [language])

  // 翻译函数
  const t = (key: string): string => {
    return translations[language][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

// 翻译文本配置
const translations: Record<Language, Record<string, string>> = {
  zh: {
    // 导航栏
    'nav.tools': 'Tools',
    'nav.notes': 'Notes',
    'nav.about': 'About',
    'nav.tools.ip': 'IP Tools',
    'nav.tools.ip.desc': 'IP地址查询与分析工具',
    'nav.tools.json': 'JSON Tools',
    'nav.tools.json.desc': 'JSON数据格式化、验证与压缩',
    'nav.notes.jq': 'jq',
    'nav.notes.jq.desc': '命令行JSON处理工具',
    'nav.notes.curl': 'curl',
    'nav.notes.curl.desc': '数据传输工具',
    'nav.notes.sed': 'sed',
    'nav.notes.sed.desc': '流编辑器',
    'nav.notes.awk': 'awk',
    'nav.notes.awk.desc': '文本处理工具',
    
    // 首页
    'home.title': 'CoderABC - 开发者工具集合',
    'home.subtitle': '面向开发者和技术爱好者的在线工具与知识笔记集合网站，致力于提供高效、实用、简洁的在线服务',
    'home.tools.title': '🛠 在线工具',
    'home.tools.subtitle': '高效实用的开发工具',
    'home.tools.ip.title': 'IP Tools',
    'home.tools.ip.desc': 'IP地址查询、格式转换和分析工具',
    'home.tools.json.title': 'JSON Tools',
    'home.tools.json.desc': 'JSON数据格式化、验证与压缩工具',
    'home.notes.title': '📝 技术笔记',
    'home.notes.subtitle': '实用的命令行工具指南',
    'home.notes.jq.title': 'jq Tour',
    'home.notes.jq.desc': '命令行JSON处理工具使用指南',
    'home.notes.curl.title': 'curl Tour', 
    'home.notes.curl.desc': '数据传输工具使用指南',
    'home.notes.sed.title': 'sed Tour',
    'home.notes.sed.desc': '流编辑器使用指南',
    'home.notes.awk.title': 'awk Tour',
    'home.notes.awk.desc': '文本处理工具使用指南',
    'home.button.explore': '开始探索',
    
    // Tools页面
    'tools.title': '🛠 在线工具',
    'tools.subtitle': '高效实用的开发工具集合，帮助您提升工作效率，简化日常开发任务',
    'tools.explore': '立即使用',
    'tools.coming-soon': '更多工具',
    'tools.coming-soon.desc': '我们正在开发更多实用工具，敬请期待！',
    
    // Notes页面
    'notes.title': '📝 技术笔记',
    'notes.subtitle': '实用的命令行工具学习指南，帮助您掌握强大的文本处理和数据操作技能',
    'notes.start-learning': '开始学习',
    'notes.about.title': '关于技术笔记',
    'notes.about.what': '这里有什么？',
    'notes.about.what.desc': '我们提供常用命令行工具的详细使用指南，包括语法说明、实际示例和最佳实践，帮助您快速上手并精通这些工具。',
    'notes.about.why': '为什么学习？',
    'notes.about.why.desc': '掌握这些命令行工具可以大大提升您的工作效率，无论是数据处理、文本操作还是系统管理，都能让您事半功倍。',
    'notes.about.tip': '提示：每个工具都提供了从基础到高级的完整学习路径，建议按顺序学习。',
    
    // About页面
    'about.title': '关于 CoderABC',
    'about.subtitle': '面向开发者和技术爱好者的在线工具与知识笔记集合',
    'about.intro.title': '项目简介',
    'about.intro.desc1': 'CoderABC 是一个专为开发者和技术爱好者打造的在线工具与知识笔记集合网站。我们致力于提供高效、实用、简洁的在线服务，帮助开发者提高工作效率。',
    'about.intro.desc2': '网站包含多种实用工具，如IP查询、JSON格式化等，同时提供了常用命令行工具的使用笔记，如jq、curl、sed、awk等。所有功能都经过精心设计，确保在各种设备上都能良好运行。',
    'about.features.title': '功能列表',
    'about.features.tools.title': '🛠 在线工具',
    'about.features.tools.ip': 'IP Tools - IP地址查询与分析工具',
    'about.features.tools.json': 'JSON Tools - JSON数据格式化、验证与压缩',
    'about.features.tools.more': '更多工具正在开发中...',
    'about.features.notes.title': '📝 技术笔记',
    'about.features.notes.jq': 'jq - 命令行JSON处理工具使用指南',
    'about.features.notes.curl': 'curl - 数据传输工具使用指南',
    'about.features.notes.sed': 'sed - 流编辑器使用指南',
    'about.features.notes.awk': 'awk - 文本处理工具使用指南',
    'about.features.notes.more': '更多笔记正在完善中...',
    'about.made': 'Made with',
    'about.team': 'by CoderABC Team',
    'about.visit': '访问地址:',
    
    // jq Tour页面
    'jq.page.title': 'jq JSON处理工具学习指南',
    'jq.tour.title': 'jq Tour',
    'jq.hide.toc': '隐藏目录',
    'jq.show.toc': '显示目录',
    'jq.getting.started': '开始使用',
    'jq.installation': '如何安装',
    'jq.basic.intro': '基本介绍',
    'jq.basic.usage': '基础用法',
    'jq.basic.syntax': '基本语法',
    'jq.field.access': '字段访问',
    'jq.array.operations': '数组操作',
    'jq.filtering': '条件过滤',
    'jq.advanced': '高级技巧',
    'jq.complex.queries': '复杂查询',
    'jq.data.transform': '数据转换',
    'jq.functions': '函数用法',
    'jq.tips': '实用技巧',
    'jq.common.patterns': '常用模式',
    'jq.performance': '性能优化',
    'jq.debugging': '调试技巧',
    
    // curl Tour页面
    'curl.page.title': 'curl 数据传输工具学习指南',
    'curl.tour.title': 'curl Tour',
    'curl.hide.toc': '隐藏目录',
    'curl.show.toc': '显示目录',
    'curl.getting.started': '开始使用',
    'curl.installation': '如何安装',
    'curl.basic.intro': '基本介绍',
    'curl.basic.usage': '基础用法',
    'curl.get.requests': 'GET 请求',
    'curl.post.requests': 'POST 请求',
    'curl.headers': '请求头',
    'curl.data.sending': '发送数据',
    'curl.advanced': '高级功能',
    'curl.authentication': '身份验证',
    'curl.file.operations': '文件操作',
    'curl.proxy.settings': '代理设置',
    'curl.tips': '实用技巧',
    'curl.common.scenarios': '常见场景',
    'curl.troubleshooting': '故障排除',
    'curl.performance': '性能调优',
    
    // sed Tour页面
    'sed.page.title': 'sed 流编辑器学习指南',
    'sed.tour.title': 'sed Tour',
    'sed.hide.toc': '隐藏目录',
    'sed.show.toc': '显示目录',
    'sed.getting.started': '开始使用',
    'sed.installation': '如何安装',
    'sed.basic.intro': '基本介绍',
    'sed.basic.usage': '基础用法',
    'sed.basic.syntax': '基本语法',
    'sed.substitution': '文本替换',
    'sed.deletion': '删除操作',
    'sed.insertion': '插入操作',
    'sed.advanced': '高级技巧',
    'sed.regex': '正则表达式',
    'sed.addressing': '地址定位',
    'sed.scripting': '脚本编写',
    'sed.tips': '实用技巧',
    'sed.common.patterns': '常用模式',
    'sed.performance': '性能优化',
    'sed.examples': '实例演示',
    
    // awk Tour页面
    'awk.page.title': 'awk 文本处理工具学习指南',
    'awk.tour.title': 'awk Tour',
    'awk.hide.toc': '隐藏目录',
    'awk.show.toc': '显示目录',
    'awk.getting.started': '开始使用',
    'awk.installation': '如何安装',
    'awk.basic.intro': '基本介绍',
    'awk.basic.usage': '基础用法',
    'awk.basic.syntax': '基本语法',
    'awk.patterns': '模式匹配',
    'awk.actions': '动作执行',
    'awk.variables': '变量使用',
    'awk.advanced': '高级技巧',
    'awk.functions': '函数用法',
    'awk.arrays': '数组处理',
    'awk.control.flow': '流程控制',
    'awk.tips': '实用技巧',
    'awk.text.processing': '文本处理',
    'awk.data.analysis': '数据分析',
    'awk.scripting': '脚本编程',
    
    // IP Tools页面
    'ip.tools.page.title': 'IP工具集合',
    'ip.tools.title': 'IP 工具集合',
    'ip.tools.description': '强大的IP地址查询、分析和转换工具集合，支持IPv4/IPv6处理',
    'ip.geolocation.title': 'IP 地理位置查询',
    'ip.geolocation.description': '查询IP地址的详细信息，包括地理位置、ISP、ASN等',
    'ip.geolocation.features.location': '地理位置',
    'ip.geolocation.features.isp': 'ISP信息',
    'ip.geolocation.features.asn': 'ASN信息',
    'ip.geolocation.features.map': '内嵌地图',
    'ip.converter.title': 'IP 格式转换',
    'ip.converter.description': '支持IPv4/IPv6与各种数值格式的相互转换',
    'ip.converter.features.ipv4': 'IPv4/IPv6',
    'ip.converter.features.endian': '大小端序',
    'ip.converter.features.int32': 'int32/uint32',
    'ip.converter.features.base': '多进制转换',
    'ip.range.title': 'IP 段查询',
    'ip.range.description': '查询IP地址段的详细信息和范围',
    'ip.range.features.cidr': 'CIDR计算',
    'ip.range.features.range': 'IP范围',
    'ip.range.features.mask': '子网掩码',
    'ip.range.features.network': '网络地址',
    'ip.tools.use.now': '立即使用',
    
    // JSON Tools页面
    'json.tools.page.title': 'JSON工具集合',
    'json.tools.title': 'JSON 工具集合',
    'json.tools.description': '强大的JSON数据处理工具集合，支持格式化、验证、压缩等功能',
    'json.formatter.title': 'JSON 格式化',
    'json.formatter.description': '美化和格式化JSON数据，提升可读性',
    'json.formatter.features.format': '代码美化',
    'json.formatter.features.highlight': '语法高亮',
    'json.formatter.features.fold': '代码折叠',
    'json.formatter.features.error': '错误提示',
    'json.validator.title': 'JSON 验证器',
    'json.validator.description': '验证JSON数据的语法正确性',
    'json.validator.features.syntax': '语法检查',
    'json.validator.features.error': '错误定位',
    'json.validator.features.schema': '模式验证',
    'json.validator.features.repair': '自动修复',
    'json.compressor.title': 'JSON 压缩',
    'json.compressor.description': '压缩JSON数据，减少文件大小',
    'json.compressor.features.minify': '代码压缩',
    'json.compressor.features.size': '大小对比',
    'json.compressor.features.preserve': '保持结构',
    'json.compressor.features.batch': '批量处理',
    'json.tools.use.now': '立即使用',
    
    // IP Geolocation页面
    'ip.geolocation.page.title': 'IP地理位置查询工具',
    'ip.geolocation.breadcrumb': '返回IP工具',
    'ip.geolocation.header.title': 'IP 地理位置查询',
    'ip.geolocation.header.desc': '查询IP地址的地理位置信息、ISP等详细数据',
    'ip.geolocation.input.placeholder': '请输入IP地址，例如：8.8.8.8',
    'ip.geolocation.button.get.my.ip': '获取我的IP',
    'ip.geolocation.button.search': '查询位置',
    'ip.geolocation.location.info': '位置信息',
    'ip.geolocation.network.info': '网络信息',
    'ip.geolocation.ip.address': 'IP地址',
    'ip.geolocation.country': '国家/地区',
    'ip.geolocation.region': '地区',
    'ip.geolocation.city': '城市',
    'ip.geolocation.coordinates': '坐标',
    'ip.geolocation.timezone': '时区',
    'ip.geolocation.isp': 'ISP',
    'ip.geolocation.organization': '组织',
    'ip.geolocation.asn': 'ASN',
    'ip.geolocation.loading': '查询中...',
    'ip.geolocation.error.invalid': '请输入有效的IP地址',
    'ip.geolocation.error.failed': '查询失败，请稍后重试',
    'ip.geolocation.error.get.ip': '获取IP地址失败，请手动输入',
    
    // IP Converter页面
    'ip.converter.page.title': 'IP格式转换工具',
    'ip.converter.breadcrumb': '返回IP工具',
    'ip.converter.header.title': 'IP 格式转换',
    'ip.converter.header.desc': '支持IPv4/IPv6与各种数值格式的相互转换',
    'ip.converter.input.placeholder': '输入IP地址或数值，支持多行批量转换',
    'ip.converter.button.convert': '转换',
    'ip.converter.button.clear': '清空',
    'ip.converter.button.copy': '复制',
    'ip.converter.format.ipv4': 'IPv4地址',
    'ip.converter.format.decimal': '十进制',
    'ip.converter.format.binary': '二进制',
    'ip.converter.format.hex': '十六进制',
    'ip.converter.format.octal': '八进制',
    'ip.converter.format.int32': '有符号32位整数',
    'ip.converter.format.uint32': '无符号32位整数',
    'ip.converter.format.big.endian': '大端序',
    'ip.converter.format.little.endian': '小端序',
    'ip.converter.examples.title': '支持的格式',
    'ip.converter.examples.desc': '支持以下格式的输入和转换：',
    
    // IP Range页面
    'ip.range.page.title': 'IP段查询工具',
    'ip.range.breadcrumb': '返回IP工具',
    'ip.range.header.title': 'IP 段查询',
    'ip.range.header.desc': '查询IP地址段的详细信息和范围',
    'ip.range.input.placeholder': '输入CIDR格式，例如：192.168.1.0/24',
    'ip.range.button.query': '查询',
    'ip.range.network.info': '网络信息',
    'ip.range.network.address': '网络地址',
    'ip.range.broadcast.address': '广播地址',
    'ip.range.subnet.mask': '子网掩码',
    'ip.range.wildcard.mask': '通配符掩码',
    'ip.range.total.hosts': '总主机数',
    'ip.range.usable.hosts': '可用主机数',
    'ip.range.first.host': '第一个主机',
    'ip.range.last.host': '最后一个主机',
    'ip.range.ip.class': 'IP类别',
  },
  en: {
    // Navigation
    'nav.tools': 'Tools',
    'nav.notes': 'Notes',
    'nav.about': 'About',
    'nav.tools.ip': 'IP Tools',
    'nav.tools.ip.desc': 'IP address query and analysis tools',
    'nav.tools.json': 'JSON Tools',
    'nav.tools.json.desc': 'JSON data formatting, validation and compression',
    'nav.notes.jq': 'jq',
    'nav.notes.jq.desc': 'Command-line JSON processor',
    'nav.notes.curl': 'curl',
    'nav.notes.curl.desc': 'Data transfer tool',
    'nav.notes.sed': 'sed',
    'nav.notes.sed.desc': 'Stream editor',
    'nav.notes.awk': 'awk',
    'nav.notes.awk.desc': 'Text processing tool',
    
    // Home
    'home.title': 'CoderABC - Developer Tools Collection',
    'home.subtitle': 'Online tools and knowledge notes collection website for developers and tech enthusiasts, committed to providing efficient, practical, and simple online services',
    'home.tools.title': '🛠 Online Tools',
    'home.tools.subtitle': 'Efficient and practical development tools',
    'home.tools.ip.title': 'IP Tools',
    'home.tools.ip.desc': 'IP address query, format conversion and analysis tools',
    'home.tools.json.title': 'JSON Tools',
    'home.tools.json.desc': 'JSON data formatting, validation and compression tools',
    'home.notes.title': '📝 Technical Notes',
    'home.notes.subtitle': 'Practical command-line tools guide',
    'home.notes.jq.title': 'jq Tour',
    'home.notes.jq.desc': 'Command-line JSON processor usage guide',
    'home.notes.curl.title': 'curl Tour',
    'home.notes.curl.desc': 'Data transfer tool usage guide',
    'home.notes.sed.title': 'sed Tour',
    'home.notes.sed.desc': 'Stream editor usage guide',
    'home.notes.awk.title': 'awk Tour',
    'home.notes.awk.desc': 'Text processing tool usage guide',
    'home.button.explore': 'Start Exploring',
    
    // Tools页面
    'tools.title': '🛠 Online Tools',
    'tools.subtitle': 'Efficient and practical development tools collection to help you improve work efficiency and simplify daily development tasks',
    'tools.explore': 'Use Now',
    'tools.coming-soon': 'More Tools',
    'tools.coming-soon.desc': 'We are developing more practical tools, stay tuned!',
    
    // Notes页面
    'notes.title': '📝 Technical Notes',
    'notes.subtitle': 'Practical command-line tool learning guides to help you master powerful text processing and data manipulation skills',
    'notes.start-learning': 'Start Learning',
    'notes.about.title': 'About Technical Notes',
    'notes.about.what': 'What\'s here?',
    'notes.about.what.desc': 'We provide detailed usage guides for common command-line tools, including syntax explanations, practical examples, and best practices to help you quickly get started and master these tools.',
    'notes.about.why': 'Why learn?',
    'notes.about.why.desc': 'Mastering these command-line tools can greatly improve your work efficiency, whether it\'s data processing, text operations, or system management, you can achieve twice the result with half the effort.',
    'notes.about.tip': 'Tip: Each tool provides a complete learning path from basic to advanced, it is recommended to learn in order.',
    
    // About page
    'about.title': 'About CoderABC',
    'about.subtitle': 'Online tools and knowledge notes collection for developers and tech enthusiasts',
    'about.intro.title': 'Project Introduction',
    'about.intro.desc1': 'CoderABC is an online tools and knowledge notes collection website designed for developers and tech enthusiasts. We are committed to providing efficient, practical, and simple online services to help developers improve work efficiency.',
    'about.intro.desc2': 'The website includes various practical tools such as IP query, JSON formatting, etc., and also provides usage notes for common command-line tools like jq, curl, sed, awk, etc. All features are carefully designed to ensure good performance on various devices.',
    'about.features.title': 'Feature List',
    'about.features.tools.title': '🛠 Online Tools',
    'about.features.tools.ip': 'IP Tools - IP address query and analysis tools',
    'about.features.tools.json': 'JSON Tools - JSON data formatting, validation and compression',
    'about.features.tools.more': 'More tools are under development...',
    'about.features.notes.title': '📝 Technical Notes',
    'about.features.notes.jq': 'jq - Command-line JSON processor usage guide',
    'about.features.notes.curl': 'curl - Data transfer tool usage guide',
    'about.features.notes.sed': 'sed - Stream editor usage guide',
    'about.features.notes.awk': 'awk - Text processing tool usage guide',
    'about.features.notes.more': 'More notes are being improved...',
    'about.made': 'Made with',
    'about.team': 'by CoderABC Team',
    'about.visit': 'Visit:',
    
    // jq Tour pages
    'jq.page.title': 'jq JSON Processor Learning Guide',
    'jq.tour.title': 'jq Tour',
    'jq.hide.toc': 'Hide Contents',
    'jq.show.toc': 'Show Contents',
    'jq.getting.started': 'Getting Started',
    'jq.installation': 'Installation',
    'jq.basic.intro': 'Basic Introduction',
    'jq.basic.usage': 'Basic Usage',
    'jq.basic.syntax': 'Basic Syntax',
    'jq.field.access': 'Field Access',
    'jq.array.operations': 'Array Operations',
    'jq.filtering': 'Filtering',
    'jq.advanced': 'Advanced Features',
    'jq.complex.queries': 'Complex Queries',
    'jq.data.transform': 'Data Transformation',
    'jq.functions': 'Functions',
    'jq.tips': 'Practical Tips',
    'jq.common.patterns': 'Common Patterns',
    'jq.performance': 'Performance Optimization',
    'jq.debugging': 'Debugging Tips',
    
    // curl Tour pages
    'curl.page.title': 'curl Data Transfer Tool Learning Guide',
    'curl.tour.title': 'curl Tour',
    'curl.hide.toc': 'Hide Contents',
    'curl.show.toc': 'Show Contents',
    'curl.getting.started': 'Getting Started',
    'curl.installation': 'Installation',
    'curl.basic.intro': 'Basic Introduction',
    'curl.basic.usage': 'Basic Usage',
    'curl.get.requests': 'GET Requests',
    'curl.post.requests': 'POST Requests',
    'curl.headers': 'Headers',
    'curl.data.sending': 'Sending Data',
    'curl.advanced': 'Advanced Features',
    'curl.authentication': 'Authentication',
    'curl.file.operations': 'File Operations',
    'curl.proxy.settings': 'Proxy Settings',
    'curl.tips': 'Practical Tips',
    'curl.common.scenarios': 'Common Scenarios',
    'curl.troubleshooting': 'Troubleshooting',
    'curl.performance': 'Performance Tuning',
    
    // sed Tour pages
    'sed.page.title': 'sed Stream Editor Learning Guide',
    'sed.tour.title': 'sed Tour',
    'sed.hide.toc': 'Hide Contents',
    'sed.show.toc': 'Show Contents',
    'sed.getting.started': 'Getting Started',
    'sed.installation': 'Installation',
    'sed.basic.intro': 'Basic Introduction',
    'sed.basic.usage': 'Basic Usage',
    'sed.basic.syntax': 'Basic Syntax',
    'sed.substitution': 'Text Substitution',
    'sed.deletion': 'Deletion Operations',
    'sed.insertion': 'Insertion Operations',
    'sed.advanced': 'Advanced Features',
    'sed.regex': 'Regular Expressions',
    'sed.addressing': 'Addressing',
    'sed.scripting': 'Scripting',
    'sed.tips': 'Practical Tips',
    'sed.common.patterns': 'Common Patterns',
    'sed.performance': 'Performance Optimization',
    'sed.examples': 'Examples',
    
    // awk Tour pages
    'awk.page.title': 'awk Text Processing Tool Learning Guide',
    'awk.tour.title': 'awk Tour',
    'awk.hide.toc': 'Hide Contents',
    'awk.show.toc': 'Show Contents',
    'awk.getting.started': 'Getting Started',
    'awk.installation': 'Installation',
    'awk.basic.intro': 'Basic Introduction',
    'awk.basic.usage': 'Basic Usage',
    'awk.basic.syntax': 'Basic Syntax',
    'awk.patterns': 'Pattern Matching',
    'awk.actions': 'Actions',
    'awk.variables': 'Variables',
    'awk.advanced': 'Advanced Features',
    'awk.functions': 'Functions',
    'awk.arrays': 'Array Processing',
    'awk.control.flow': 'Control Flow',
    'awk.tips': 'Practical Tips',
    'awk.text.processing': 'Text Processing',
    'awk.data.analysis': 'Data Analysis',
    'awk.scripting': 'Scripting',
    
    // IP Tools pages
    'ip.tools.page.title': 'IP Tools Collection',
    'ip.tools.title': 'IP Tools Collection',
    'ip.tools.description': 'Powerful IP address query, analysis and conversion tools collection, supporting IPv4/IPv6 processing',
    'ip.geolocation.title': 'IP Geolocation Query',
    'ip.geolocation.description': 'Query detailed information of IP addresses, including geolocation, ISP, ASN, etc.',
    'ip.geolocation.features.location': 'Geolocation',
    'ip.geolocation.features.isp': 'ISP Info',
    'ip.geolocation.features.asn': 'ASN Info',
    'ip.geolocation.features.map': 'Embedded Map',
    'ip.converter.title': 'IP Format Conversion',
    'ip.converter.description': 'Support mutual conversion between IPv4/IPv6 and various numeric formats',
    'ip.converter.features.ipv4': 'IPv4/IPv6',
    'ip.converter.features.endian': 'Endianness',
    'ip.converter.features.int32': 'int32/uint32',
    'ip.converter.features.base': 'Multi-base Conversion',
    'ip.range.title': 'IP Range Query',
    'ip.range.description': 'Query detailed information and range of IP address blocks',
    'ip.range.features.cidr': 'CIDR Calculation',
    'ip.range.features.range': 'IP Range',
    'ip.range.features.mask': 'Subnet Mask',
    'ip.range.features.network': 'Network Address',
    'ip.tools.use.now': 'Use Now',
    
    // JSON Tools pages
    'json.tools.page.title': 'JSON Tools Collection',
    'json.tools.title': 'JSON Tools Collection',
    'json.tools.description': 'Powerful JSON data processing tools collection, supporting formatting, validation, compression and more',
    'json.formatter.title': 'JSON Formatter',
    'json.formatter.description': 'Beautify and format JSON data to improve readability',
    'json.formatter.features.format': 'Code Beautification',
    'json.formatter.features.highlight': 'Syntax Highlighting',
    'json.formatter.features.fold': 'Code Folding',
    'json.formatter.features.error': 'Error Hints',
    'json.validator.title': 'JSON Validator',
    'json.validator.description': 'Validate the syntax correctness of JSON data',
    'json.validator.features.syntax': 'Syntax Check',
    'json.validator.features.error': 'Error Location',
    'json.validator.features.schema': 'Schema Validation',
    'json.validator.features.repair': 'Auto Repair',
    'json.compressor.title': 'JSON Compressor',
    'json.compressor.description': 'Compress JSON data to reduce file size',
    'json.compressor.features.minify': 'Code Minification',
    'json.compressor.features.size': 'Size Comparison',
    'json.compressor.features.preserve': 'Preserve Structure',
    'json.compressor.features.batch': 'Batch Processing',
    'json.tools.use.now': 'Use Now',
    
    // IP Geolocation pages
    'ip.geolocation.page.title': 'IP Geolocation Query Tool',
    'ip.geolocation.breadcrumb': 'Back to IP Tools',
    'ip.geolocation.header.title': 'IP Geolocation Query',
    'ip.geolocation.header.desc': 'Query geographical location information, ISP and other detailed data of IP addresses',
    'ip.geolocation.input.placeholder': 'Please enter an IP address, e.g.: 8.8.8.8',
    'ip.geolocation.button.get.my.ip': 'Get My IP',
    'ip.geolocation.button.search': 'Search Location',
    'ip.geolocation.location.info': 'Location Information',
    'ip.geolocation.network.info': 'Network Information',
    'ip.geolocation.ip.address': 'IP Address',
    'ip.geolocation.country': 'Country/Region',
    'ip.geolocation.region': 'Region',
    'ip.geolocation.city': 'City',
    'ip.geolocation.coordinates': 'Coordinates',
    'ip.geolocation.timezone': 'Timezone',
    'ip.geolocation.isp': 'ISP',
    'ip.geolocation.organization': 'Organization',
    'ip.geolocation.asn': 'ASN',
    'ip.geolocation.loading': 'Querying...',
    'ip.geolocation.error.invalid': 'Please enter a valid IP address',
    'ip.geolocation.error.failed': 'Query failed, please try again later',
    'ip.geolocation.error.get.ip': 'Failed to get IP address, please enter manually',
    
    // IP Converter pages
    'ip.converter.page.title': 'IP Format Conversion Tool',
    'ip.converter.breadcrumb': 'Back to IP Tools',
    'ip.converter.header.title': 'IP Format Conversion',
    'ip.converter.header.desc': 'Support mutual conversion between IPv4/IPv6 and various numeric formats',
    'ip.converter.input.placeholder': 'Enter IP address or numeric value, supports multi-line batch conversion',
    'ip.converter.button.convert': 'Convert',
    'ip.converter.button.clear': 'Clear',
    'ip.converter.button.copy': 'Copy',
    'ip.converter.format.ipv4': 'IPv4 Address',
    'ip.converter.format.decimal': 'Decimal',
    'ip.converter.format.binary': 'Binary',
    'ip.converter.format.hex': 'Hexadecimal',
    'ip.converter.format.octal': 'Octal',
    'ip.converter.format.int32': 'Signed 32-bit Integer',
    'ip.converter.format.uint32': 'Unsigned 32-bit Integer',
    'ip.converter.format.big.endian': 'Big Endian',
    'ip.converter.format.little.endian': 'Little Endian',
    'ip.converter.examples.title': 'Supported Formats',
    'ip.converter.examples.desc': 'Supports input and conversion of the following formats:',
    
    // IP Range pages
    'ip.range.page.title': 'IP Range Query Tool',
    'ip.range.breadcrumb': 'Back to IP Tools',
    'ip.range.header.title': 'IP Range Query',
    'ip.range.header.desc': 'Query detailed information and range of IP address blocks',
    'ip.range.input.placeholder': 'Enter CIDR format, e.g.: 192.168.1.0/24',
    'ip.range.button.query': 'Query',
    'ip.range.network.info': 'Network Information',
    'ip.range.network.address': 'Network Address',
    'ip.range.broadcast.address': 'Broadcast Address',
    'ip.range.subnet.mask': 'Subnet Mask',
    'ip.range.wildcard.mask': 'Wildcard Mask',
    'ip.range.total.hosts': 'Total Hosts',
    'ip.range.usable.hosts': 'Usable Hosts',
    'ip.range.first.host': 'First Host',
    'ip.range.last.host': 'Last Host',
    'ip.range.ip.class': 'IP Class',
  }
}
